using JetBrains.Annotations;
using UnityEngine;

namespace Code.Services.ScreenResolutionService
{
    
    //This code generated by AI.
    [UsedImplicitly]
    public class ScreenResolutionService : IScreenResolutionService
    {
        private readonly Resolution[] _availableResolutions;
        private int _currentResolutionIndex;

        public void SetResolution(int width, int height, bool isFullScreen)
        {
            Screen.SetResolution(width, height, isFullScreen);
        }

        public ScreenResolutionService()
        {
            _availableResolutions = Screen.resolutions;
            _currentResolutionIndex = FindCurrentResolutionIndex();
        }

        public void SetResolution(int resolutionIndex)
        {
            if (resolutionIndex >= 0 && resolutionIndex < _availableResolutions.Length)
            {
                _currentResolutionIndex = resolutionIndex;
                Resolution resolution = _availableResolutions[resolutionIndex];
                Screen.SetResolution(resolution.width, resolution.height, Screen.fullScreen);
            }
        }
        
        public void SetFullscreen(bool isFullscreen)
        {
            Screen.fullScreen = isFullscreen;
        }
        
        public Resolution[] GetAvailableResolutions()
        {
            return _availableResolutions;
        }
        
        public Resolution GetCurrentResolution()
        {
            return _availableResolutions[_currentResolutionIndex];
        }

        public int GetCurrentResolutionIndex()
        {
            return _currentResolutionIndex;
        }

        private int FindCurrentResolutionIndex()
        {
            Resolution currentResolution = Screen.currentResolution;
            for (int i = 0; i < _availableResolutions.Length; i++)
            {
                if (_availableResolutions[i].width == currentResolution.width &&
                    _availableResolutions[i].height == currentResolution.height)
                {
                    return i;
                }
            }

            return 0;
        }
    }
}
